FROM openjdk:8-jdk-alpine

RUN apk --update add tzdata
RUN echo "America/Bogota" > /etc/timezone
RUN ln -snf /usr/share/zoneinfo/America/Bogota /etc/localtime && echo America/Bogota > /etc/timezone

ARG DEPENDENCY=./target
COPY ${DEPENDENCY}/apisaludcitasinorden.jar /home/apisaludcitasinorden.jar
ENV APP_NAME=APP_NAME
ENV AZURE_STORAGE_URL_FILE=AZURE_STORAGE_URL_FILE
ENV BLOB_STORAGE_ACCOUNT=BLOB_STORAGE_ACCOUNT
ENV BLOB_STORAGE_CONTAINER=BLOB_STORAGE_CONTAINER
ENV BLOB_STORAGE_DOWNLOAD=BLOB_STORAGE_DOWNLOAD
ENV BLOB_STORAGE_PATH=BLOB_STORAGE_PATH
ENV DEPLOYMENT_PORT=DEPLOYMENT_PORT
ENV ENVIROMENTS=ENVIROMENTS
ENV KEY_INSIGHTS=KEY_INSIGHTS
ENV MYSQL_CONNECTION_SPRING=MYSQL_CONNECTION_SPRING
ENV MYSQL_PASSWORD=MYSQL_PASSWORD
ENV MYSQL_USER=MYSQL_USER
ENV PATH_VALIDATIONS=PATH_VALIDATIONS
ENV EMAIL_REPLY=EMAIL_REPLY

ENV ENVIROMENTS=${ENVIROMENTS}
ENTRYPOINT ["java","-jar","-Dspring.profiles.active=develop","/home/apisaludcitasinorden.jar"]