server:
  port: 80
  servlet:
    context-path: /v1.0/
spring:
  profiles: develop
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://colsdigitaldbproduccionsalud.mysql.database.azure.com:3306/portalsalud?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: colsadmin@colsdigitaldbproduccionsalud
#    password: 123456789!aA
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://cols-db-digqa-util.mysql.database.azure.com:3306/portalsalud?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: colsadmin@cols-db-digqa-util
    password: 123456789!aA
  application:
    name: api-salud-citas-sinorden
    version: develop
  sleuth:
     sampler:
        probability: 1
  main: 
     allow-bean-definition-overriding: true
azure:
  application-insights: #cols-ai-digptest-empresas-backend
    instrumentation-key: d3c4e8a8-71f3-4cf4-a8fd-98ed2758e00f     
eureka:
  client:
    serviceUrl:
      defaultZone: https://admin:admin@col-as-digprod-service-registry.azurewebsites.net/eureka/
  enabled: false
  instance:
    securePortEnabled: true
    nonSecurePortEnabled: false
    statusPageUrlPath: swagger-ui.html
    healthCheckUrlPath: health
ribbon:
  eureka:
    enabled: false
api:
  back:
    legado:
      get: get
      post: post
apigee:
#  url: https://colsubsidio-prod.apigee.net
  url: https://colsubsidio-test.apigee.net
  urlMock: http://www.mocky.io/v2/
  token:
    url: /oauth/client_credential/accesstoken
#    clienteId: 9ZajtAJ3i9BLMDri8UxTaQTsZFv47oo8
    clienteId: 5A0amJxdlqDKntk1HbMAW7IxNrOW2026
#    clienteSecreto: WHIaAwMCiMwrvZFp
    clienteSecreto: A3Wtl1gzqXUcM5rQ
    maxTimeInMillis: 300000 #300000 millis = 5 minutes
  path:
    auth: /oauth/client_credential/accesstoken
    logger: /api/v1/tecnologia/logger  
colsubsidio:
  elasticSearch:
    index: api-erp-manager
    type: api-azure
  procedures:
    schedule: 
      insert: CALL PR_COLSSALUD_SCHEDULE_I_RESERVATION(:p_date, :p_order, :p_reservation, :p_specialty, :p_state, :p_type_document, :p_document_number, :p_data, :p_cancellation, :p_modified, :p_modified_by, :p_created, :p_created_by)
      update: CALL PR_COLSSALUD_SCHEDULE_U_RESERVATION(:p_order, :p_reservation, :p_specialty, :p_state, :p_type_document, :p_document_number, :p_cancellation, :p_modified, :p_modified_by)
      select: CALL PR_COLSSALUD_SCHEDULE_S_RESERVATION()
    logs:
      insert: CALL PR_COLSSALUD_I_LOGS(:accion, :message)
scheduled:
  agendamiento:
    tarea:
      enable: false
      borrarcitas: 300000
---
spring:
  profiles: release
  application:
    name: ${APP_NAME}
    version: ${APP_VERSION}
  sleuth:
     sampler:
        probability: 1
azure:
  application-insights:
    instrumentation-key: ${AZURE_INSIGHT_KEY}
eureka:
  client:
    serviceUrl:
      defaultZone: https://admin:admin@col-as-digprod-service-registry.azurewebsites.net/eureka/
  enabled: true
  instance:
    securePortEnabled: true
    nonSecurePortEnabled: false
    statusPageUrlPath: swagger-ui.html
    healthCheckUrlPath: health
ribbon:
  eureka:
    enabled: true  
api:
  back:
    legado:
      get: ${LEGADO_GET}
      post: ${LEGADO_POST}
apigee:
  url: ${APIGEE}
  token:
    url: /oauth/client_credential/accesstoken
    clienteId: ${APIGEE_CLIENT_ID}
    clienteSecreto: ${APIGEE_CLIENT_SECRET}
    maxTimeInMillis: 300000 #300000 millis = 5 minutes
  path:
    auth: /oauth/client_credential/accesstoken
    logger: /api/v1/tecnologia/logger  
colsubsidio:
  elasticSearch:
    index: ${ELASTICSEARCH_INDEX}
    type: ${ELASTICSEARCH_TYPE}
